-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 18:48:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tour_agency
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `tour_agency` ;

-- -----------------------------------------------------
-- Schema tour_agency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tour_agency` DEFAULT CHARACTER SET latin1 ;
USE `tour_agency` ;

-- -----------------------------------------------------
-- Table `tour_agency`.`country`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`country` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`country` (
  `country_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `area` DECIMAL(20) NOT NULL,
  `population` INT NOT NULL,
  `created_at` DATE NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`language`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`language` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`language` (
  `language_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `language_id_UNIQUE` (`language_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`language_has_country`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`language_has_country` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`language_has_country` (
  `language_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `speakers` INT NULL,
  INDEX `fk_language_has_country_country1_idx` (`country_id` ASC) ,
  INDEX `fk_language_has_country_language_idx` (`language_id` ASC) ,
  CONSTRAINT `fk_language_has_country_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `tour_agency`.`language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_language_has_country_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `tour_agency`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`river`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`river` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`river` (
  `river_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `length` DECIMAL(20) NOT NULL,
  `image` MEDIUMTEXT NULL,
  PRIMARY KEY (`river_id`),
  UNIQUE INDEX `river_id_UNIQUE` (`river_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`country_has_river`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`country_has_river` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`country_has_river` (
  `country_id` INT NOT NULL,
  `river_id` INT NOT NULL,
  `length_in_country` DECIMAL(20) NOT NULL,
  INDEX `fk_country_has_river_river1_idx` (`river_id` ASC) ,
  INDEX `fk_country_has_river_country1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_country_has_river_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `tour_agency`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_has_river_river1`
    FOREIGN KEY (`river_id`)
    REFERENCES `tour_agency`.`river` (`river_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`lake`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`lake` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`lake` (
  `lake_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `area` DECIMAL(20) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `image` MEDIUMTEXT NULL,
  PRIMARY KEY (`lake_id`),
  UNIQUE INDEX `lake_id_UNIQUE` (`lake_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`lake_has_country`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`lake_has_country` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`lake_has_country` (
  `lake_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  INDEX `fk_lake_has_country_country1_idx` (`country_id` ASC) ,
  INDEX `fk_lake_has_country_lake1_idx` (`lake_id` ASC) ,
  CONSTRAINT `fk_lake_has_country_lake1`
    FOREIGN KEY (`lake_id`)
    REFERENCES `tour_agency`.`lake` (`lake_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lake_has_country_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `tour_agency`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`city`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`city` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`city` (
  `city_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `area` DECIMAL(20) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `image` MEDIUMTEXT NULL,
  `country_id` INT NOT NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC) ,
  UNIQUE INDEX `city_id_UNIQUE` (`city_id` ASC) ,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `tour_agency`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`sights`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`sights` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`sights` (
  `sights_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATE NULL,
  `image` MEDIUMTEXT NULL,
  `description` MEDIUMTEXT NULL,
  `city_id` INT NOT NULL,
  `address` MEDIUMTEXT NULL,
  PRIMARY KEY (`sights_id`),
  INDEX `fk_sights_city1_idx` (`city_id` ASC) ,
  UNIQUE INDEX `sights_id_UNIQUE` (`sights_id` ASC) ,
  CONSTRAINT `fk_sights_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`museum`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`museum` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`museum` (
  `museum_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `opens_at` TIME NULL,
  `closes_at` TIME NULL,
  `description` MEDIUMTEXT NULL,
  `image` MEDIUMTEXT NULL,
  `city_id` INT NOT NULL,
  `address` MEDIUMTEXT NULL,
  PRIMARY KEY (`museum_id`),
  INDEX `fk_museum_city1_idx` (`city_id` ASC) ,
  UNIQUE INDEX `museum_id_UNIQUE` (`museum_id` ASC) ,
  CONSTRAINT `fk_museum_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`theatre`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`theatre` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`theatre` (
  `theatre_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `image` MEDIUMTEXT NULL,
  `address` MEDIUMTEXT NULL,
  `opens_at` TIME NULL,
  `closes_at` TIME NULL,
  `city_id` INT NOT NULL,
  `phone` MEDIUMTEXT NULL,
  PRIMARY KEY (`theatre_id`),
  INDEX `fk_theatre_city1_idx` (`city_id` ASC) ,
  UNIQUE INDEX `theatre_id_UNIQUE` (`theatre_id` ASC) ,
  CONSTRAINT `fk_theatre_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`play`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`play` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`play` (
  `play_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `starts_at` DATE NULL,
  `ends_at` DATE NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`play_id`),
  UNIQUE INDEX `play_id_UNIQUE` (`play_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`play_has_language`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`play_has_language` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`play_has_language` (
  `language_id` INT NOT NULL,
  `play_id` INT NOT NULL,
  INDEX `fk_theatre_has_language_language1_idx` (`language_id` ASC) ,
  INDEX `fk_play_has_language_play1_idx` (`play_id` ASC) ,
  CONSTRAINT `fk_play_has_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `tour_agency`.`language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_play_has_language_play1`
    FOREIGN KEY (`play_id`)
    REFERENCES `tour_agency`.`play` (`play_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`restourant`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`restourant` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`restourant` (
  `restourant_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` MEDIUMTEXT NULL,
  `opens_at` TIME NULL,
  `closes_at` TIME NULL,
  `rate` DECIMAL(20) NULL,
  `city_id` INT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  PRIMARY KEY (`restourant_id`),
  INDEX `fk_restourant_city1_idx` (`city_id` ASC) ,
  UNIQUE INDEX `restourant_id_UNIQUE` (`restourant_id` ASC) ,
  CONSTRAINT `fk_restourant_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`hotel`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`hotel` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`hotel` (
  `hotel_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` MEDIUMTEXT NULL,
  `rate` DECIMAL(20) NULL,
  `description` MEDIUMTEXT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`hotel_id`),
  INDEX `fk_hotel_city1_idx` (`city_id` ASC) ,
  UNIQUE INDEX `hotel_id_UNIQUE` (`hotel_id` ASC) ,
  CONSTRAINT `fk_hotel_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`distance_between_cities`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`distance_between_cities` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`distance_between_cities` (
  `city_city_id` INT NOT NULL,
  `city_city_id1` INT NOT NULL,
  `distance` DECIMAL(20) NOT NULL,
  INDEX `fk_city_has_city_city2_idx` (`city_city_id1` ASC) ,
  INDEX `fk_city_has_city_city1_idx` (`city_city_id` ASC) ,
  CONSTRAINT `fk_city_has_city_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city_has_city_city2`
    FOREIGN KEY (`city_city_id1`)
    REFERENCES `tour_agency`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_agency`.`play_has_theatre`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tour_agency`.`play_has_theatre` ;

CREATE TABLE IF NOT EXISTS `tour_agency`.`play_has_theatre` (
  `play_id` INT NOT NULL,
  `theatre_id` INT NOT NULL,
  INDEX `fk_play_has_theatre_theatre1_idx` (`theatre_id` ASC) ,
  INDEX `fk_play_has_theatre_play1_idx` (`play_id` ASC) ,
  CONSTRAINT `fk_play_has_theatre_play1`
    FOREIGN KEY (`play_id`)
    REFERENCES `tour_agency`.`play` (`play_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_play_has_theatre_theatre1`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `tour_agency`.`theatre` (`theatre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into country(country_id, name, area, population, created_at, description) values (1, 'Russia', 17000000, 155000000, '1991-12-29', 'Very good city');
insert into city(city_id, name, population, area, description, image, country_id, created_at) values (1, 'Saint Petersburg', 7000000, 1, 'Very good city','image',1,'1703-01-01');
select * from country, city where country.country_id = city.country_id;